pve:
  hosts:
    proxmox:
    nas:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_python_interpreter: auto_silent

lxc:
  hosts:
    glance:
    qbittorrent:
    pi-hole:
    jellyfin:
    gitea:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_python_interpreter: auto_silent
