pve:
  hosts:
    nas:
    proxmox:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_python_interpreter: auto_silent

lxc:
  hosts:
    gitea:
    glance:
    jellyfin:
    pi-hole:
    pulse:
    qbittorrent:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_python_interpreter: auto_silent
