---
- hosts: all
  pre_tasks:
    - name: Update packages
      ansible.builtin.import_tasks: pre_tasks/update_packages.yml
      tags:
        - always

    - name: Install packages
      ansible.builtin.import_tasks: pre_tasks/install_packages.yml
      tags:
        - always

    - name: Configure config directory
      ansible.builtin.import_tasks: pre_tasks/configure_config_directory.yml
      tags:
        - always

# - hosts: proxmox
#   roles:
#     - role:

- hosts: nas
  roles:
    - role: sync-files
      tags: sync-files

- hosts: glance
  roles:
    - role: sync-files
      tags: sync-files
    - role: compose
      tags: compose

- hosts: jellyfin
  roles:
    - role: sync-files
      tags: sync-files
    - role: compose
      tags: compose

- hosts: qbittorrent
  roles:
    - role: sync-files
      tags: sync-files
    - role: compose
      tags: compose

- hosts: gitea
  roles:
    - role: sync-files
      tags: sync-files
    - role: compose
      tags: compose
