---
- hosts: nas
  roles:
    - role: update
      tags: update
    - role: sync-files
      tags: sync-files

- hosts: proxmox
  roles:
    - role: update
      tags: update

- hosts: gitea
  roles:
    - role: update
      tags: update
    - role: sync-files
      tags: sync-files
    - role: compose
      tags: compose

- hosts: glance
  roles:
    - role: update
      tags: update
    - role: sync-files
      tags: sync-files
    - role: compose
      tags: compose

- hosts: jellyfin
  roles:
    - role: update
      tags: update
    - role: sync-files
      tags: sync-files
    - role: compose
      tags: compose

- hosts: pi-hole
  roles:
    - role: update
      tags: update


- hosts: qbittorrent
  roles:
    - role: update
      tags: update
    - role: sync-files
      tags: sync-files
    - role: compose
      tags: compose
