---
- name: Install packages
  become: true
  ansible.builtin.package:
    name:
      - curl
      - eza
      - fzf
      - git
      - jq
      - lazygit
      - neovim
      - npm
      - stow
      - zoxide
      - zsh
    state: present
