---
- name: Install packages
  become: true
  block:
    - name: Install - Common
      ansible.builtin.package:
        name:
          - curl
          - eza
          - fzf
          - git
          - jq
          - lazygit
          - neovim
          - npm
          - stow
          - zoxide
          - zsh
        state: present

    - name: Install - Pi-hole
      when: inventory_hostname == 'pi-hole'
      ansible.builtin.package:
        name:
          - unbound
        state: present
